version: "3.8"

services:
  discord_bot:
    build:
      context: .
      dockerfile: Dockerfile
    container_name: discord_bot
    environment:
      - DISCORD_TOKEN=${DISCORD_TOKEN}
      - DISCORD_GUILD_ID=${DISCORD_GUILD_ID}
      - ADE_LINK=${ADE_LINK}
      - ADE_USERNAME=${ADE_USERNAME}
      - ADE_PASSWORD=${ADE_PASSWORD}
    volumes:
      - ../usr/src/app
    command: ["npm", "start"]
    restart: always